// Stable fail-closed codes for the AG-6 agent-readiness checker.
// A presented document that is the wrong shape must use one of these codes
// and must not be scored as a pass.

export const CODES = Object.freeze({
  DISCOVERY_NOT_JSON: "AG6_DISCOVERY_NOT_JSON",
  DISCOVERY_NOT_OBJECT: "AG6_DISCOVERY_NOT_OBJECT",
  DISCOVERY_WRONG_SHAPE: "AG6_DISCOVERY_WRONG_SHAPE",
  HANDSHAKE_NOT_JSON: "AG6_HANDSHAKE_NOT_JSON",
  HANDSHAKE_NOT_OBJECT: "AG6_HANDSHAKE_NOT_OBJECT",
  HANDSHAKE_NOT_JSONRPC: "AG6_HANDSHAKE_NOT_JSONRPC",
  HANDSHAKE_ID_MISMATCH: "AG6_HANDSHAKE_ID_MISMATCH",
  HANDSHAKE_MISSING_RESULT: "AG6_HANDSHAKE_MISSING_RESULT",
  HANDSHAKE_REJECTED: "AG6_HANDSHAKE_REJECTED",
  HANDSHAKE_SERVER_INFO: "AG6_HANDSHAKE_SERVER_INFO",
  HANDSHAKE_VERSION_ABSENT: "AG6_HANDSHAKE_VERSION_ABSENT",
  HANDSHAKE_VERSION_UNSUPPORTED: "AG6_HANDSHAKE_VERSION_UNSUPPORTED",
  TOOLS_LIST_NOT_JSON: "AG6_TOOLS_LIST_NOT_JSON",
  TOOLS_LIST_NOT_OBJECT: "AG6_TOOLS_LIST_NOT_OBJECT",
  TOOLS_LIST_NOT_JSONRPC: "AG6_TOOLS_LIST_NOT_JSONRPC",
  TOOLS_LIST_ID_MISMATCH: "AG6_TOOLS_LIST_ID_MISMATCH",
  TOOLS_LIST_MISSING_TOOLS: "AG6_TOOLS_LIST_MISSING_TOOLS",
  TOOLS_LIST_TOOL_SHAPE: "AG6_TOOLS_LIST_TOOL_SHAPE",
  IDENTITY_CONFLICT: "AG6_IDENTITY_CONFLICT",
  CORS_PREFLIGHT_ABSENT: "AG6_CORS_PREFLIGHT_ABSENT",
  CORS_ORIGIN_ABSENT: "AG6_CORS_ORIGIN_ABSENT",
  CORS_METHOD_ABSENT: "AG6_CORS_METHOD_ABSENT",
  CORS_HEADER_ABSENT: "AG6_CORS_HEADER_ABSENT",
  X402_NOT_JSON: "AG6_X402_NOT_JSON",
  X402_NOT_OBJECT: "AG6_X402_NOT_OBJECT",
  X402_WRONG_SHAPE: "AG6_X402_WRONG_SHAPE",
  X402_AMOUNT_NOT_ATOMIC: "AG6_X402_AMOUNT_NOT_ATOMIC",
  AGENT_CARD_NOT_JSON: "AG6_AGENT_CARD_NOT_JSON",
  AGENT_CARD_NOT_OBJECT: "AG6_AGENT_CARD_NOT_OBJECT",
  AGENT_CARD_WRONG_SHAPE: "AG6_AGENT_CARD_WRONG_SHAPE",
});

export const CODE_SET = new Set(Object.values(CODES));

export function assertCode(code) {
  if (!CODE_SET.has(code)) throw new Error(`unknown agent-readiness code ${code}`);
  return code;
}
