-- Admit the current declared MCP tool inventory into pulse_validate_delta.
-- Owning inventory: server/lib/mcp-tool-inventory.js MCP_TOOL_NAMES.
-- Generated by server/lib/pulse-store/tool-contract-sql.js.
-- Forward and rerunnable. Does not rewrite migrations 0002 or 0003
-- or the released 0005 tool contract.
-- Does not update aggregate rows, first-observed boundaries, flush ids,
-- receipt hashes, or idempotency. Does not grant customer, payment, or
-- extra role authority. CREATE OR REPLACE keeps existing function grants;
-- the statements below only re-state the service-role-only write/read posture.
-- Tool keys (7): check_ai_readiness, check_agent_readiness, generate_complete_fix_pack, plan_taskmarket_delegation, browse_taskmarket_tasks, track_taskmarket_task, project_funnel_evidence
-- Counter-map limit: 7 keys, 32 chars.

create or replace function public.pulse_validate_delta(p_delta jsonb)
returns jsonb language plpgsql immutable set search_path = '' as $$
declare
  v_schema int;
  v_tool_observed_from timestamptz;
  v_funnel_keys text[] := array['home', 'scan', 'tools', 'reports', 'guides', 'pricing'];
  v_mcp_keys text[] := array['initialize', 'tools/list', 'tools/call', 'notifications', 'other'];
  v_tool_keys text[] := array['check_ai_readiness', 'check_agent_readiness', 'generate_complete_fix_pack', 'plan_taskmarket_delegation', 'browse_taskmarket_tasks', 'track_taskmarket_task', 'project_funnel_evidence'];
begin
  if p_delta is null or jsonb_typeof(p_delta) <> 'object' then raise exception 'pulse_invalid_delta' using errcode = '22023'; end if;
  if (select count(*) from jsonb_object_keys(p_delta) k where k not in (
    'schemaVersion','total','humans','bots','aiCrawlers','mcpSurfaceGets',
    'mcpProtocolRequests','mcpProtocolMessages','mcpProtocolByMethod','mcpToolCallsObservedFrom','mcpToolCallsByName',
    'byPath','byReferer','byAiBot','funnel','sellerRepair')) > 0 then
    raise exception 'pulse_invalid_delta' using errcode = '22023';
  end if;
  v_schema := public.pulse_validate_nonneg_int(p_delta -> 'schemaVersion', 'schemaVersion')::int;
  if v_schema <> 2 then raise exception 'pulse_invalid_schema_version' using errcode = '22023'; end if;
  if jsonb_typeof(p_delta -> 'mcpToolCallsObservedFrom') <> 'string'
     or (p_delta ->> 'mcpToolCallsObservedFrom') !~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$' then
    raise exception 'pulse_invalid_field:mcpToolCallsObservedFrom' using errcode = '22023';
  end if;
  begin
    v_tool_observed_from := (p_delta ->> 'mcpToolCallsObservedFrom')::timestamptz;
  exception when others then
    raise exception 'pulse_invalid_field:mcpToolCallsObservedFrom' using errcode = '22023';
  end;
  if not isfinite(v_tool_observed_from) then
    raise exception 'pulse_invalid_field:mcpToolCallsObservedFrom' using errcode = '22023';
  end if;
  return jsonb_build_object(
    'schemaVersion',v_schema,
    'total',public.pulse_validate_nonneg_int(p_delta -> 'total','total'),
    'humans',public.pulse_validate_nonneg_int(p_delta -> 'humans','humans'),
    'bots',public.pulse_validate_nonneg_int(p_delta -> 'bots','bots'),
    'aiCrawlers',public.pulse_validate_nonneg_int(p_delta -> 'aiCrawlers','aiCrawlers'),
    'mcpSurfaceGets',public.pulse_validate_nonneg_int(p_delta -> 'mcpSurfaceGets','mcpSurfaceGets'),
    'mcpProtocolRequests',public.pulse_validate_nonneg_int(p_delta -> 'mcpProtocolRequests','mcpProtocolRequests'),
    'mcpProtocolMessages',public.pulse_validate_nonneg_int(p_delta -> 'mcpProtocolMessages','mcpProtocolMessages'),
    'mcpProtocolByMethod',public.pulse_validate_counter_map(p_delta -> 'mcpProtocolByMethod','mcpProtocolByMethod',v_mcp_keys,8,32),
    'mcpToolCallsObservedFrom',v_tool_observed_from,
    'mcpToolCallsByName',public.pulse_validate_counter_map(p_delta -> 'mcpToolCallsByName','mcpToolCallsByName',v_tool_keys,7,32),
    'byPath',public.pulse_validate_counter_map(p_delta -> 'byPath','byPath',null,200,60),
    'byReferer',public.pulse_validate_counter_map(p_delta -> 'byReferer','byReferer',null,200,96),
    'byAiBot',public.pulse_validate_counter_map(p_delta -> 'byAiBot','byAiBot',null,64,64),
    'funnel',public.pulse_validate_counter_map(p_delta -> 'funnel','funnel',v_funnel_keys,8,16),
    'sellerRepair',public.pulse_validate_seller_repair(p_delta -> 'sellerRepair'));
end; $$;

revoke all on function public.pulse_validate_delta(jsonb) from public, anon, authenticated;
revoke all on function public.pulse_apply_delta(uuid, jsonb) from public, anon, authenticated;
revoke all on function public.pulse_read_snapshot(timestamptz, timestamptz) from public, anon, authenticated;
grant execute on function public.pulse_apply_delta(uuid, jsonb) to service_role;
grant execute on function public.pulse_read_snapshot(timestamptz, timestamptz) to service_role;
